version: '3'
services:
 db-postgres:
   image: "postgres:14.0"
   environment:
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     - POSTGRES_DB=${DATABASE_NAME}
   expose:
     - "5432"
   ports:
     - "5432:5432"
 api:
   build: .
   ports:
    - "5000:5000"
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - db-postgres

