version: '3'
services:
 db-postgres:
   image: "postgres:14.0"
   environment:
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     - POSTGRES_DB=${DATABASE_NAME}
 migration:
   build: .
   environment:
     - APP_ENV=${APP_ENV}
   command: >
        sh -c "flask db migrate
        && flask db upgrade"
   depends_on:
     - db-postgres
 api:
   build: .
   ports:
    - "5000:5000"
   environment:
     - APP_ENV=${APP_ENV}
   depends_on:
     - db-postgres
     - migration

